### ISSUE TITLE
Doesn't work on Safari

### ISSUE THREAD

**Issue by maxharlow** [JamesMilnerUK/scratchmap#1]

**Comment by JamesLMilner** [comment]
Seems to be an issue with let support in 9.x : http://caniuse.com/#search=let

**Comment by maxharlow** [comment]
I'm using Safari 10

**Comment by JamesLMilner** [comment]
Weird, is there any console error?

**Comment by maxharlow** [comment]
No fetch

**Comment by maxharlow** [comment]
Safari 10.1 has it, not upgraded yet

**Comment by JamesLMilner** [comment]
I'll try and polyfill

**Comment by JamesLMilner** [comment]
Should be fixed now! Thanks polyfill.io
